//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facebook_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend
    {
        public int f_id { get; set; }
        public int user_id { get; set; }
        public int friend_id { get; set; }
    
        public virtual user_profile user_profile { get; set; }
        public virtual user_profile user_profile1 { get; set; }
    }
}
